import type { Metadata } from 'next'
import './globals.css'
import Footer from '../components/Footer'
import Navbar from '../components/navigation/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={'container mx-auto'}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
