name: CI Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

permissions:
  contents: read

env:
  NODE_VERSION: '20'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Set up Node.js for backend 
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Run backend tests
        run: npm run test
        working-directory: backend

      - name: Start backend server and wait for availability
        run: |
          npm start &
          npx wait-on http://localhost:8080
          echo "Backend server is responsive"
        working-directory: backend

  landing-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Set up Node.js for landing 
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: landing/package-lock.json

      - name: Install landing dependencies
        run: npm ci
        working-directory: landing

      - name: Build landing application
        run: npm run build
        working-directory: landing

      - name: Start landing server and wait for availability
        run: |
          npm start &
          npx wait-on http://localhost:3000
          echo "Landing server is responsive"
        working-directory: landing
