name: CI Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests 
        run: |
          cd backend
          npm run tests
