name: CI Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run backend tests
        run: |
          cd backend
          npm ci
          npm run test

      - name: Test backend startup script
        run: |
          cd backend
          npm start & 
          npx wait-on http://localhost:8080
          echo "Server is responsive"

      - name: Test landing startup script
        run: |
          cd landing
          npm ci
          npm run build
          npm start &
          npx wait-on http://localhost:3000
          echo "Landing is responsive"
